services:
  - type: web
    name: sales-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
    plan: free
    rootDir: sales-app-backend

  - type: web
    name: sales-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://sales-app-backend.onrender.com/api/v1
    plan: free
    rootDir: sales-app-frontend
